version: '2.1'

services:  
  # PostgreSQL database
  db:
    image: postgres:9.6
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis:4.0.1
    hostname: redis
    ports:
      - "6379:6379"

  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.11
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
      #- RABBITMQ_DEFAULT_VHOST=myvhost
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  # Django web server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: ./run_web.sh
    volumes:
      - .:/app  # mount current directory inside container
    ports:
      - "8000:8000"
    # set up links so that web knows about db, rabbit and redis
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - db

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./run_celery.sh
    volumes:
      - .:/app
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - rabbit

  # Swagger API description
  swagger:
    container_name: swagger-server
    build: ./src/swagger
    volumes:
      - './src/swagger:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8005:3001' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=${NODE_ENV}
    links:
      - web