# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0003_auto_20170824_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='argument',
        ),
        migrations.RemoveField(
            model_name='job',
            name='result',
        ),
    ]
