# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 19:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0004_auto_20170824_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
