# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 23:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0005_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='param',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
