# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 23:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0006_auto_20170828_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='param',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
