# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0007_auto_20170828_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='kwargs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
