# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0008_job_kwargs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('get_rss', 'get_rss'), ('send_email', 'send_email')], max_length=20),
        ),
    ]
